import star_img from "../Card_img/star_watch.svg";
export const top_ten_crypto = [
  {
    name: "XRP/USD",
    name_des: "XRP US Dollar",
    last: "0.4588",
    chg: "-0.01170",
    pre_chg: "-2.48672",
    watchlist: star_img,
  },
  {
    name: "FLOW/USD",
    name_des: "FLOW US Dollar",
    last: "0.851",
    chg: "-0.03800",
    pre_chg: "-4.27446",
    watchlist: star_img,
  },
  {
    name: "DASH/USD",
    name_des: "DASH US Dollar",
    last: "48.6",
    chg: "-0.99000",
    pre_chg: "-1.99637",
    watchlist: star_img,
  },
  {
    name: "ETH/USD",
    name_des: "Ethereum US Dollar",
    last: "1838.12",
    chg: "-31.97000",
    pre_chg: "-1.70954",
    watchlist: star_img,
  },
  {
    name: "BTC/USD",
    name_des: "Bitcoin US Dollar",
    last: "28272.12",
    chg: "-961.09000",
    pre_chg: "-3.28766",
    watchlist: star_img,
  },
  {
    name: "SOL/USD",
    name_des: "Solana US Dollar",
    last: "21.94",
    chg: "-0.80000",
    pre_chg: "-3.51803",
    watchlist: star_img,
  },
  {
    name: "AVAX/USD",
    name_des: "Avalanche Us Dollar",
    last: "16.9",
    chg: "-0.20000",
    pre_chg: "-1.16959",
    watchlist: star_img,
  },
  {
    name: "XMR/USD",
    name_des: "Monero US Dollar",
    last: "153.3",
    chg: "-2.10000",
    pre_chg: "-1.35135",
    watchlist: star_img,
  },
  {
    name: "LTC/US",
    name_des: "Litecoin US Dollar",
    last: "86.93",
    chg: "-1.29000",
    pre_chg: "-1.46225",
    watchlist: star_img,
  },
  {
    name: "BNB/US",
    name_des: "Binance coin US Dollar",
    last: "329.6",
    chg: "-7.90000",
    pre_chg: "-2.34074",
    watchlist: star_img,
  }
];
let optionsDate = 
{ 
    // weekday: 'long', 
    year: 'numeric', 
    month: 'long', 
    day: 'numeric'
};
var latest_date=new Date().toLocaleDateString('en-US',optionsDate);
export const top_ten_heading={
    heading:'TOP 10 CRYPTOCURRENCY MOVERS',
    update_date:"Last Updated "+latest_date,
    name_h: "Name",
    last_h: "Last",
    chg_h: "Chg",
    pre_chg_h: "Chg",
    watchlist_h: "Watchlist",
  }

 export const top_ten_stock = [
  {
    name: "CMG",
    name_des: "Chipotle Mexican Grill Inc",
    last: "2044.23499",
    chg: "-23.38513",
    pre_chg: "-1.13102",
    watchlist: star_img,
    url:'/stock-quote/CMG:NYSE',
  },
  {
    name: "MCD",
    name_des: "McDonald's Crops",
    last: "298.25",
    chg: "+2.50000",
    pre_chg: "+0.84531",
    watchlist: star_img,
  },
  {
    name: "IBM",
    name_des: "International Business Machines Crops",
    last: "126.425",
    chg: "+0.01500",
    pre_chg: "+0.01187",
    watchlist: star_img,
  },
  {
    name: "META",
    name_des: "Meta Platforms,Inc",
    last: "242.715",
    chg: "+2.39499",
    pre_chg: "+0.99658",
    watchlist: star_img,
  },
  {
    name: "MSFT",
    name_des: "Microsoft Corp",
    last: "306.87",
    chg: "-0.39001",
    pre_chg: "-0.12693",
    watchlist: star_img,
  },
  {
    name: "TSLA",
    name_des: "Tesla,Inc",
    last: "162.25999",
    chg: "-2.05000",
    pre_chg: "-1.24764",
    watchlist: star_img,
  },
  {
    name: "SPOT",
    name_des: "GoldSpot Discoveries Corp",
    last: "0.23",
    chg: "+0.01000",
    pre_chg: "+4.54546",
    watchlist: star_img,
  },
  {
    name: "GOOG",
    name_des: "Alphabet Inc",
    last: "108.48",
    chg: "+0.26000",
    pre_chg: "+0.24025",
    watchlist: star_img,
  },
  {
    name: "LVS",
    name_des: "Las Vegas Sands Crop",
    last: "64.655",
    chg: "+0.80500",
    pre_chg: "+1.26077",
    watchlist: star_img,
  },
];
export const top_ten_heading1={
    heading:'TOP 10 SOARING STOCKS',
    update_date:"Last Updated "+latest_date,
    name_h: "Name",
    last_h: "Last",
    chg_h: "Chg",
    pre_chg_h: "Chg",
    watchlist_h: "Watchlist",
  }